# Generated by Django 3.0.5 on 2020-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discont',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
